# batch config

label:          'Comic: La Agonía de Rasu Ñiti / Wañunayaq Rasu Ñit'imanta'
description:    'Practice collection for aperitiiif service'
# attribution:    

presentation_api_url: 'https://aperitiiif-presentation-api-store.s3.us-east-1.amazonaws.com'
image_api_url:        'https://d1b7k5w7yjwpfg.cloudfront.net/iiif/2'

records:
  file: 'src/records.csv'
  defaults:
    logo: 'src/data/WR01/01.png'
    # source: 'https://commons.wikimedia.org/wiki/Category:Prints_by_Katsukawa_Shunsh%C5%8D_in_the_Rijksmuseum_Amsterdam'
